config/routes.rb
Rails.application.routes.draw do
  resources :notifications, only: [:index]

  get 'newsletters/create'
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }

  devise_scope :user do
    post "/users/enter_private_mode" => "users/registrations#enter_private_mode"
  end

  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # Sources
  resources :sources, only: [:index, :new, :create, :show, :edit, :destroy, :update] do
    resources :comments, only: [:create], as: "create_comment"
  end

  get "feed", to: "sources#feed", as: "feed"
  get "feed/:page", to: "sources#get_sources_for_friends_feed", as: "lazy_friends_feed"

  get "discover", to: "sources#discover", as: "discover_feed"
  get "discover/:page", to: "sources#get_sources_for_discover_feed", as: "lazy_discover_feed"


  # Quotes
  resources :quotes, only: [:new, :create, :show, :destroy] do
    resources :comments, only: [:create], as: "create_comment_from_feed"
  end

  resources :comments, only: [:new, :create, :show, :index, :destroy]
  resources :comment_votes, only: [:new, :create, :destroy]


  # Pages
  get "search", to: "pages#search"
  get "user/:id/overview", to: "pages#user_profile_overview", as: "user_profile_overview"
  
  get "user/:id/overview/:page", to: "pages#get_sources_for_profile_overview", as: "lazy_profile_overview_feed"
  
  get "user/:id/followers", to: "pages#user_profile_followers", as: "user_profile_followers"
  get "user/:id/following", to: "pages#user_profile_following", as: "user_profile_following"
  get "coming-soon", to: "pages#coming_soon", as: "coming_soon"
  get "all-user-suggestions", to: "pages#all_user_suggestions", as: "all_user_suggestions" 
  get "about-us", to: "pages#about_us", as: "about_us"


  # Folders
  resources :folders, only: [:show, :edit, :new, :create]

  # Relationships
  resources :relationships, only: [:update, :destroy]
  post "relationships/:id", to: "relationships#create", as: "create_relationship"
  delete "relationship/:id", to: "relationships#destroy", as: "delete_relationship"

  # Contact
  resources :contacts, only: [:create]

  # API
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :sources, only: [:create, :update]
      resources :quotes, only: [:create, :destroy]
      resources :comments, only: [:create]
      resources :tags, only: [:index, :create]

    end
  end

  get '/user' => "sources#feed", :as => :user_root
  resources :newsletters
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :quote
  belongs_to :user
  has_many :comments, foreign_key: :parent_id, dependent: :destroy
  has_many :comment_votes, dependent: :destroy


  validates :content, presence: true

  # Adds up all the values of all comment votes on a comment. Don't confuse this with comment_votes_count,
  # which returns total nr of comment votes on a comment instead of aggregating their value.
  def comment_votes_aggregate
    if comment_votes
      CommentVote.where(comment_id: self.id).map(&:value).inject(0){|sum,x| sum + x }      
    else
      return 0
    end
  end

  # Returns true if liked by user, false if downvoted by user, nil if not liked or disliked by user
  def liked_by_user?(current_user)
    value = CommentVote.where(comment_id: self.id, user_id: current_user.id)&.first&.value
    if value == 1
      return true
    elsif value == -1
      return false
    else
      return nil
    end
  end

  def sort_by_upvotes
    raise
    self.sort_by do |comment|
      comment.comment_votes_count
    end
  end

end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < Api::V1::BaseController

  def create
    current_user = User.find(comment_post_request_params[:user_id])
    @quote = Quote.find(comment_post_request_params[:quote_id])
    print @quote
    authorize @quote


    @comment = Comment.new(content: comment_post_request_params[:comment])
    print(@comment)
    authorize @comment
    @comment.quote = @quote
    @comment.user = current_user
    @comment.save!
    render :show

  end

  def comment_post_request_params
    params.require(:comment_post_request).permit(:user_id, :quote_id, :comment)
  end

  def render_error
    render json: { errors: @source.errors.full_messages },
      status: :unprocessable_entity
  end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    if params["comment"]["quote_id"]

      @quote = Quote.find(params["comment"]["quote_id"])
    else
      @quote = Quote.find(params[:quote_id])
    end

    @parent_id = params["comment"]["parent_id"]&.to_i

    if !params[:source_id].nil?
      @source = Source.find(params[:source_id])
    else
      @source = Source.find(@quote.source_id)
    end

   if params["comment"]["content"]
      @comment = Comment.new(content: params["comment"]["content"], source: params["comment"]["source"])

   else
      @comment = Comment.new(content: params[:content]) # how do I build this with strong_comment_params
   end

    authorize @comment

    @comment.quote = @quote
    @comment.user = current_user
    @comment.parent_id = @parent_id

    if @comment.save!
      redirect_to request.referer + "#comment-#{@comment.id}"
    else
      redirect_back(fallback_location: root_path)
    end

      if @comment.parent_id == nil #&& @comment.quote.user != current_user
        CommentNotification.with(comment: @comment).deliver(@comment.quote.user)
      elsif @comment.parent_id != nil #&& Comment.find(@parent_id).user != current_user
        CommentReplyNotification.with(comment: @comment).deliver(Comment.find(@parent_id).user)
      end
  end

  def show(notification=nil)
    @comment = Comment.find(params[:id])
    @new_comment = Comment.new
    authorize @comment
  end

  def strong_comment_params
    params.require(:comment).permit(:content)
  end

  def destroy
    @comment = Comment.find_by_id(params[:id].to_i)
    authorize @comment
    @comment.destroy!
    redirect_to request.referrer
  end

end

app/views/comments/_comment-reply.html.erb
<% comments.to_a.sort_by(&:comment_votes_aggregate).reverse.each do |comment| %>
<span class="comment-anchor" id="comment-<%= comment.id %>"></span>
  <div class="comment-div" id="">
    <div class="comment">
      <div class="votes">
        <% if comment.liked_by_user?(current_user) == nil %>
          <span class="vote-anchor" id="vote-<%= comment.id %>"></span>
          <%= link_to "", comment_votes_path(comment), class: "fas fa-sort-up upvote", method: :create %>
          <span class="number-of-votes"><%= comment.comment_votes_aggregate %></span>
          <%= link_to "", comment_vote_path(comment), class: "fas fa-sort-down downvote", method: :delete %>

        <% elsif comment.liked_by_user?(current_user) == true %>
          <span class="vote-anchor" id="vote-<%= comment.id %>"></span>
          <%= link_to "", comment_votes_path(comment), class: "fas fa-sort-up upvote", id:"active-vote", method: :create %>
          <span class="number-of-votes"><%= comment.comment_votes_aggregate %></span>
          <%= link_to "", comment_vote_path(comment), class: "fas fa-sort-down downvote", method: :delete %>

        <% elsif comment.liked_by_user?(current_user) == false %>
          <span class="vote-anchor" id="vote-<%= comment.id %>"></span>
          <%= link_to "", comment_votes_path(comment), class: "fas fa-sort-up upvote", method: :create %>
          <span class="number-of-votes"><%= comment.comment_votes_aggregate %></span>
          <%= link_to "", comment_vote_path(comment), class: "fas fa-sort-down downvote", id:"active-vote", method: :delete %>
        <% end %>
      </div>

      <%= link_to user_profile_overview_path(comment.user) do %>
        <div class="comment-avatar">
          <% if comment.user.photo.attached? %>
            <%= cl_image_tag comment.user.photo.key, class: "" %>
          <% else %>
            <%= cl_image_tag "#{@default_profile_image}", class: "" %>
          <% end %>
        </div>
      <% end %>
      
      <div class="box-and-btn">
        

          <div class="comment-content-box">
            <div class="user-and-time">
            <%= link_to user_profile_overview_path(comment.user) do %>
              <p class="user comment-text"><%= comment.user.username %></p>
            <% end %>
              <span class="time"><%= time_ago_in_words(comment.created_at).gsub('about','').gsub(" days", "d").gsub("less than a", "1").gsub(" minutes", "m").gsub(" hours", "h") %></span>
            </div>
            <%= link_to comment_path(comment) do %>
              <p class="comment-text"><%= comment.content %></p>
            <% end %>

            <% unless comment.source == nil %>
              <%= link_to "Source", comment.source, :class => "comment-source", target: "_blank" %>
            <% end %>

          </div>

       

        <div class="reply-btn">
          <%= link_to "#", data: {toggle: "modal", target: "#modal-#{comment.id}"} do  %>
            Reply
          <% end %>
        </div>
      </div>


      <!-- Delete Sub Comment -->
      <% if comment.user == current_user %>
        <div class="comment-delete">
          <%= link_to comment_path(comment), method: :delete do %>
            <i class="far fa-trash-alt"></i>
          <% end %>
        </div>
      <% end %>

      <% @new_comment = Comment.new %>
      <div class="modal fade" id="modal-<%= comment.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content p-1">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Reply to <span>"<%= comment.content %>"</span></h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <div class="">
                 <%= form_for(@new_comment) do |f| %>
                   <%= f.label "Comment:" %>
                   <%= f.text_field :content %>
                   <%= f.label "Source:" %>
                   <%= f.text_field :source %>
                   <%= f.hidden_field :parent_id, :value => comment.id %>
                   <%= f.hidden_field :quote_id, :value => comment.quote.id %>
                   <%= f.submit class: 'comment_submit' %>
                 <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>


    </div>
    <%= render partial: "comments/comment-reply", locals: { comments: comment.comments } %>
  </div>
<% end %>

app/views/comments/_feed-comments.html.erb
<div class="quotes-and-comments">
  <% source.quotes.each do |quote| %>
    <div class="quote-and-comment">
      <div class="quote">
        <i class="fas fa-quote-left"></i>
        <p class=""><span><%= quote.content %></span></p>
      </div>

      <% if quote.comments.empty? %>
        <div class="quote-comment-btn">
          <%= link_to "#", data: {toggle: "modal", target: "#modal-#{quote.id}"} do  %>
            Be the first to comment!
          <% end %>
        </div>
      <% else %>
        <div class="quote-comment-btn">
          <%= link_to "#", data: {toggle: "modal", target: "#modal-#{quote.id}"} do  %>
            Comment
          <% end %>
        </div>

      <% end %>

      <!-- Comments -->
      <div class="comments-div">
        <%= render partial: "comments/comment-reply", locals: { comments: quote.comments.where(parent_id:nil) } %>
      </div>
    </div>

    <% @new_comment = Comment.new %>
    <div class="modal fade" id="modal-<%= quote.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content p-1">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Comment on <span>"<%= quote.content %>"</span></h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <div class="">
               <%= form_for(@new_comment) do |f| %>
                 <%= f.label "Comment:" %>
                 <%= f.text_field :content %>
                 <%= f.label "Source:" %>
                 <%= f.text_field :source %>
                 <%= f.hidden_field :quote_id, :value => quote.id %>
                 <%= f.submit class: 'comment_submit' %>
               <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/comments/_reply.html.erb
<div style="margin-left: <%= 22 %>px"> 

    <%= link_to comment_path(id: comment.id) do %>
        <h2><%= comment.content %></h2>
    <% end %>

     <% unless comment.source == nil %>
        <%= link_to "Source", comment.source, :class => "comment-source", target: "_blank" %>
    <% end %>

    <% if comment.comments.empty? %>
        <i class="far fa-trash-alt"></i>
        <%= link_to "Delete this Comment",
            comment_path(comment),
            method: :delete %>
    <% end %>

    <%= comment.comment_votes_aggregate %>

    <%= link_to comment_votes_path(comment), method: :create do %>
        <i class="fas fa-sort-up"></i>
    <% end %>
    <%= link_to comment_vote_path(comment), method: :delete do %>
        <i class="fas fa-sort-down"></i>
    <% end %>
</div>

app/views/comments/show.html.erb
<div class="quote">
  <i class="fas fa-quote-left"></i>
  <p class=""><span><%= @comment.quote.content %></span></p>
</div>

<div class="comments-div">
  <%= render partial: "comments/comment-reply", locals: { comments: [@comment] } %>
</div>