config/routes.rb
Rails.application.routes.draw do
  resources :notifications, only: [:index]

  get 'newsletters/create'
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }

  devise_scope :user do
    post "/users/enter_private_mode" => "users/registrations#enter_private_mode"
  end

  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # Sources
  resources :sources, only: [:index, :new, :create, :show, :edit, :destroy, :update] do
    resources :comments, only: [:create], as: "create_comment"
  end

  get "feed", to: "sources#feed", as: "feed"
  get "feed/:page", to: "sources#get_sources_for_friends_feed", as: "lazy_friends_feed"

  get "discover", to: "sources#discover", as: "discover_feed"
  get "discover/:page", to: "sources#get_sources_for_discover_feed", as: "lazy_discover_feed"


  # Quotes
  resources :quotes, only: [:new, :create, :show, :destroy] do
    resources :comments, only: [:create], as: "create_comment_from_feed"
  end

  resources :comments, only: [:new, :create, :show, :index, :destroy]
  resources :comment_votes, only: [:new, :create, :destroy]


  # Pages
  get "search", to: "pages#search"
  get "user/:id/overview", to: "pages#user_profile_overview", as: "user_profile_overview"
  
  get "user/:id/overview/:page", to: "pages#get_sources_for_profile_overview", as: "lazy_profile_overview_feed"
  
  get "user/:id/followers", to: "pages#user_profile_followers", as: "user_profile_followers"
  get "user/:id/following", to: "pages#user_profile_following", as: "user_profile_following"
  get "coming-soon", to: "pages#coming_soon", as: "coming_soon"
  get "all-user-suggestions", to: "pages#all_user_suggestions", as: "all_user_suggestions" 
  get "about-us", to: "pages#about_us", as: "about_us"


  # Folders
  resources :folders, only: [:show, :edit, :new, :create]

  # Relationships
  resources :relationships, only: [:update, :destroy]
  post "relationships/:id", to: "relationships#create", as: "create_relationship"
  delete "relationship/:id", to: "relationships#destroy", as: "delete_relationship"

  # Contact
  resources :contacts, only: [:create]

  # API
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :sources, only: [:create, :update]
      resources :quotes, only: [:create, :destroy]
      resources :comments, only: [:create]
      resources :tags, only: [:index, :create]

    end
  end

  get '/user' => "sources#feed", :as => :user_root
  resources :newsletters
end

app/views/shared/_avatar.html.erb
<% if user.photo.attached? %>
  <%= cl_image_tag user.photo.key, class: "avatar" %>
<% elsif @default_profile_image%>
  <%= cl_image_tag "#{@default_profile_image}", class: "avatar" %>
<% else %>
  <%= cl_image_tag "Profile_avatar_placeholder_large_t0udob", class: "avatar" %>
<% end %>

<!-- source.user.photo.key -->

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-danger alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_global-search.html.erb
<div class="global-search-field-div">
  <i class="fas fa-search"></i>

  <%= form_tag search_path, method: :get do %>
    <%= text_field_tag :global_search_query, params[:global_search_query], onfocus: " let value = this.value; this.value = null; this.value=value", class: "global-search-form", placeholder: "Search Capture" %>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>

    </ul>
  </div>
</div>

<% Folder.where(user: current_user).each do |folder| %>
<ul>
  <li><%= link_to folder.folder_name, folder_path(folder) %></li>
</ul>
<% end %>

app/views/shared/_page-title.html.erb
<div class="page-title-div">
  <div class="page-title">
    <p class="mb-2"><%= @heading %></p>
    <!-- <span class="page-title-line"></span> -->
  </div>
</div>

app/views/shared/_profile-user-header.html.erb
<div class="d-flex align-items-center">

  <div class="user-show-avatar">
    <% if @user.photo.attached? %>
      <%= cl_image_tag @user.photo.key, class: "avatar-user-show dropdown-toggle",
        id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %> 
    <% else %>
      <%= cl_image_tag "b08hxPY_jhyrxg", class: "avatar-user-show dropdown-toggle",
        id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %> 
    <% end %>
  </div>

  <div>
    <h1 class="profile-username"> <%= @user.first_name %> <%= @user.last_name %> </h1>
    <% if (current_user != @user) %>
      <div class="follow-btn-div">
        <% if ((Relationship.where(asker: current_user, receiver: @user, status: 1).size > 0) ) %>
          <%= link_to "Unfollow", delete_relationship_path(@user, current_user), method: :delete, class: "follow-btn" %>
        <% else %>
          <%= link_to "Follow", create_relationship_path(@user, current_user), method: :create, class: "follow-btn" %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

  <div class="d-flex">
    <div class=" user-link-div <%= "user-link-div-active" if current_page?(user_profile_overview_path(@user)) %>">
      <%= link_to "Overview", user_profile_overview_path(@user), class: 'user-link'  %>
    </div>

    <div class="user-link-div <%= "user-link-div-active" if current_page?(user_profile_followers_path(@user)) %>">
      <%= link_to "Followers", user_profile_followers_path(@user), class: "user-link"  %>
    </div>

    <div class="user-link-div <%= "user-link-div-active" if current_page?(user_profile_following_path(@user)) %>">
      <%= link_to "Following", user_profile_following_path(@user), class: "user-link"  %>
    </div>
  </div>

app/views/shared/_sidebar-rest.html.erb
      <%= link_to root_path do  %>
      <%= cl_image_tag("pngtree-camera-hand--logo-template-with-line-art-style-image_128418_hdebp6",
      width: 110, height: 110, crop: :fit, class: "logo-sidebar") %>
      <% end %>

<div class="div-main-links-sidebar">
    <ul class="nav-bar-links">
      <%= link_to sources_path, class: "nav-bar-links" do  %>
      <% if current_page?(sources_path) %>
      <li class="POS-ABS"><i class="fas fa-caret-right"></i></li>
      <% end %>
      <li><i class="fas fa-home"></i></li>
      <li class="home-btn-navbar"><strong>Home</strong></li>
      <% end %>
    </ul>

    <ul class="nav-bar-links">
      <li> <i class="fas fa-bell"></i></li>
      <li class=""><strong>Notifications</strong></li>
    </ul>

    <ul class="nav-bar-links">
      <li> <i class="fas fa-search"></i></li>
      <li class=""><strong>Search</strong></li>
    </ul>

    <ul class="nav-bar-links">
      <%= link_to user_profile_overview_path(current_user), class: "nav-bar-links" do  %>
      <% if (current_page?(user_profile_overview_path(current_user)) || current_page?(user_profile_followers_path(current_user))||current_page?(user_profile_following_path(current_user))) %>
      <li class="POS-ABS"><i class="fas fa-caret-right"></i></li>
      <% end %>
      <li><i class="fas fa-user"></i></li>
      <li class="home-btn-navbar"><strong>Profile</strong></li>
      <% end %>
    </ul>
</div>

  <ul class="ul-new-button">
  <li class="d-flex dropdown align-items-center">
    <div class="d-flex new-button align-items-center" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <p class="plus-icon-new-button"><i class="fas fa-plus"></i></p>
        <p class="new-text-new-button">New</p>
      </div>

    <div class="dropdown-menu dropdown-menu-left" aria-labelledby="navbarDropdown">
      <%= link_to "Folder", new_folder_path, class: "dropdown-item" %>
      <%= link_to "Quote", new_quote_path, class: "dropdown-item" %>
    </div>
  </li>
</ul>

<div class="all-folders-in-sidebar">

  <ul class="ul-all-folders">
  <% folders.each do |folder| %>
    <%= link_to folder_path(folder), class: "folder-link ul-text-decoration" do %>
      <div class="div-folder-in-sidebar <%= "active" if current_page?(folder_path(folder)) %>">
    <% if current_page?(folder_path(folder)) %>
    <li class="POS-ABS"><i class="fas fa-caret-right"></i></li>
    <% end %>
        <li class="folder-in-sidebar"> <i class="fa fa-archive"></i> <%= folder.folder_name %></li>
      </div>
    <% end %>
  <% end %>
  </ul>
</div>

app/views/shared/_title-bar.html.erb
<div class="heading-div text-center">
  <!-- No Heading -->
  <% if @heading.nil? %>
      <h1 class="no-heading"><span class="">__</span></h1>

  <!-- Profile Heading -->
  <% elsif @profile_show_page == true %>
    <div class="d-flex align-items-center justify-content-center">
      <div>
        <% @user = User.find(params[:id]) %>
        <% if @user.photo.attached? %>
          <%= cl_image_tag @user.photo.key, class: "heading mr-3 profile-heading-avatar" %>
        <% else %>
          <%= cl_image_tag "#{@default_profile_image}", class: "heading mr-3 profile-heading-avatar" %>
        <% end %>
      </div>
      <div>
        <h1 class="heading m-0"><span class=""><%= @heading %></span></h1>
      </div>
    </div>

  <!-- Normal Heading -->
  <% else %>
    <h1 class="heading"><span class=""><%= @heading %></span></h1>
  <% end %>
</div>

app/views/shared/_user-list.html.erb
<% users.each do |user| %>
  <div class="user-card">

    <div class="d-flex align-items-center">
      <div class="user-avatar">
        <% if user.photo.attached? %>
          <%= cl_image_tag user.photo.key, class: "" %>
        <% else %>
          <%= cl_image_tag "#{@default_profile_image}", class: "" %>
        <% end %>
      </div>

      <div class="username-and-tags">
        <%= link_to "#{user.username}", user_profile_overview_path(user), class: "username" %> <br>
        <p class="tags">
          <% user.tags.each do |tag| %>
            <% if tag == user.tags.last %>
              <%= link_to "##{tag.name}", "#", class: "tag"  %>
            <% else %>
              <%= link_to "##{tag.name},", "#", class: "tag"  %>
            <% end %>
          <% end %>
        </p>
      </div>
    </div>

    <div class="follow-btn-div">
      <% unless user == current_user %>
        <% if (Relationship.where(asker: current_user, receiver: user, status: 1).size > 0) %>
          <%= link_to delete_relationship_path(user, current_user), method: :delete, class: "follow-btn" do %>
            <span class="follow-text"><i class="fas fa-minus"></i></i> Unfollow </span>
          <% end %>

        <% else %>
          <%= link_to create_relationship_path(user, current_user), method: :create, class: "follow-btn" do %>
            <span class="follow-text"><i class="fas fa-plus"></i> Follow </span>
          <% end %>
        <% end %>
      <% end %>
    </div>


  </div>

<% end %>

app/views/shared/_user-profile-header.html.erb
<div class="d-flex align-items-center">

  <div class="user-show-avatar">
    <% if @user.photo.attached? %>
      <%= cl_image_tag @user.photo.key, class: "avatar-user-show dropdown-toggle",
        id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
    <% else %>
        <%= cl_image_tag "b08hxPY_jhyrxg", class: ".avatar-user-show dropdown-toggle",
        id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
    <% end %>
  </div>

  <div>
    <h1> <%= @user.first_name %> <%= @user.last_name %> </h1>

    <% if (current_user != @user) %>
    <div class="follow-btn-div">
      <% if ((Relationship.where(asker: current_user, receiver: @user, status: 1).size > 0) ) %>
        <%= link_to "Unfollow", delete_relationship_path(@user, current_user), method: :delete, class: "follow-btn" %>
      <% else %>
        <%= link_to "Follow", create_relationship_path(@user, current_user), method: :create, class: "follow-btn" %>
      <% end %>
    </div>
    <% end %>

  </div>
</div>

  <div class="d-flex">

    <div class=" user-link-div <%= "user-link-div-active" if current_page?(user_profile_overview_path(@user)) %>">
      <%= link_to "Overview", user_profile_overview_path(@user), class: 'user-link'  %>
    </div>

    <div class="user-link-div <%= "user-link-div-active" if current_page?(user_profile_followers_path(@user)) %>">
      <%= link_to "Followers", user_profile_followers_path(@user), class: "user-link"  %>
    </div>

    <div class="user-link-div <%= "user-link-div-active" if current_page?(user_profile_following_path(@user)) %>">
      <%= link_to "Following", user_profile_following_path(@user), class: "user-link"  %>
    </div>

  </div>