config/routes.rb
Rails.application.routes.draw do
  resources :notifications, only: [:index]

  get 'newsletters/create'
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }

  devise_scope :user do
    post "/users/enter_private_mode" => "users/registrations#enter_private_mode"
  end

  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # Sources
  resources :sources, only: [:index, :new, :create, :show, :edit, :destroy, :update] do
    resources :comments, only: [:create], as: "create_comment"
  end

  get "feed", to: "sources#feed", as: "feed"
  get "feed/:page", to: "sources#get_sources_for_friends_feed", as: "lazy_friends_feed"

  get "discover", to: "sources#discover", as: "discover_feed"
  get "discover/:page", to: "sources#get_sources_for_discover_feed", as: "lazy_discover_feed"


  # Quotes
  resources :quotes, only: [:new, :create, :show, :destroy] do
    resources :comments, only: [:create], as: "create_comment_from_feed"
  end

  resources :comments, only: [:new, :create, :show, :index, :destroy]
  resources :comment_votes, only: [:new, :create, :destroy]


  # Pages
  get "search", to: "pages#search"
  get "user/:id/overview", to: "pages#user_profile_overview", as: "user_profile_overview"
  
  get "user/:id/overview/:page", to: "pages#get_sources_for_profile_overview", as: "lazy_profile_overview_feed"
  
  get "user/:id/followers", to: "pages#user_profile_followers", as: "user_profile_followers"
  get "user/:id/following", to: "pages#user_profile_following", as: "user_profile_following"
  get "coming-soon", to: "pages#coming_soon", as: "coming_soon"
  get "all-user-suggestions", to: "pages#all_user_suggestions", as: "all_user_suggestions" 
  get "about-us", to: "pages#about_us", as: "about_us"


  # Folders
  resources :folders, only: [:show, :edit, :new, :create]

  # Relationships
  resources :relationships, only: [:update, :destroy]
  post "relationships/:id", to: "relationships#create", as: "create_relationship"
  delete "relationship/:id", to: "relationships#destroy", as: "delete_relationship"

  # Contact
  resources :contacts, only: [:create]

  # API
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :sources, only: [:create, :update]
      resources :quotes, only: [:create, :destroy]
      resources :comments, only: [:create]
      resources :tags, only: [:index, :create]

    end
  end

  get '/user' => "sources#feed", :as => :user_root
  resources :newsletters
end

app/views/shared/navbars/_landing-page-navbar.html.erb
<div class="global-nav">
  <div class="landing-page-navbar">

      <%= link_to sources_path, class: "remove-underline" do  %>
        <div class="logo-and-name">
          <%= cl_image_tag "Screenshot_2021-02-14_at_00.59.44_mafn2e", class: "logo", width: 35 %>
          <h1 class="capture-logo-title">Capture</h1>
        </div>
      <% end %>

      <div class="right-links">
        <div class="about-us">
          <%= link_to "About us", about_us_path  %>
        </div>

        <div class="log-in">
          <%= link_to "Log In", new_user_session_path  %>
        </div>

        <div class="sign-up">
          <%= link_to "Get Started", new_user_registration_path  %>
        </div>
      </div>

  </div>
</div>

app/views/shared/navbars/_top-navbar.html.erb
<div class="global-nav">
  <div class="top-navbar">

    <!-- Logo and Name -->
    <div class="logo-and-name">
      <%= link_to sources_path, class: "remove-underline" do  %>
        <div class="logo-name-d-flex">
          <%= cl_image_tag "Screenshot_2021-02-14_at_00.59.44_mafn2e", class: "logo", width: 35 %>
          <h1 class="capture-logo-title">Capture</h1>
        </div>
      <% end %>
    </div>
    <!--  -->

    <div class="top-navbar-left">
      <% if current_user.private_mode %>
        <div class="private_mode_tag">
          <i class="fas fa-lock mr-2"></i><span>Private Session</span>
        </div>
      <% end %>
    </div>

    <div class="top-navbar-right">
        <div class="about-us">
        <%= link_to "About us", about_us_path  %>
      </div>
    </div>

    <div class="top-navbar-global-search">
      <%= render 'shared/global-search' %>
    </div>

  </div>

</div>

app/views/shared/navbars/_widget-navbar.html.erb
<!-- Links -->
<div class="side-navbar">
  <div class="sidebar-links">
  
    <% @users.each do |user| %>
        <%= link_to create_relationship_path(user, current_user), method: :create, class: "" do  %>
            <div class="d-flex sidebar-link ">
                <i class="far fa-plus-square"></i>                
                <p class="">Follow</p><%= user.email %>
            </div>
        <% end %>
    <% end %>

  </div>
</div>