config/routes.rb
Rails.application.routes.draw do
  resources :notifications, only: [:index]

  get 'newsletters/create'
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }

  devise_scope :user do
    post "/users/enter_private_mode" => "users/registrations#enter_private_mode"
  end

  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # Sources
  resources :sources, only: [:index, :new, :create, :show, :edit, :destroy, :update] do
    resources :comments, only: [:create], as: "create_comment"
  end

  get "feed", to: "sources#feed", as: "feed"
  get "feed/:page", to: "sources#get_sources_for_friends_feed", as: "lazy_friends_feed"

  get "discover", to: "sources#discover", as: "discover_feed"
  get "discover/:page", to: "sources#get_sources_for_discover_feed", as: "lazy_discover_feed"


  # Quotes
  resources :quotes, only: [:new, :create, :show, :destroy] do
    resources :comments, only: [:create], as: "create_comment_from_feed"
  end

  resources :comments, only: [:new, :create, :show, :index, :destroy]
  resources :comment_votes, only: [:new, :create, :destroy]


  # Pages
  get "search", to: "pages#search"
  get "user/:id/overview", to: "pages#user_profile_overview", as: "user_profile_overview"
  
  get "user/:id/overview/:page", to: "pages#get_sources_for_profile_overview", as: "lazy_profile_overview_feed"
  
  get "user/:id/followers", to: "pages#user_profile_followers", as: "user_profile_followers"
  get "user/:id/following", to: "pages#user_profile_following", as: "user_profile_following"
  get "coming-soon", to: "pages#coming_soon", as: "coming_soon"
  get "all-user-suggestions", to: "pages#all_user_suggestions", as: "all_user_suggestions" 
  get "about-us", to: "pages#about_us", as: "about_us"


  # Folders
  resources :folders, only: [:show, :edit, :new, :create]

  # Relationships
  resources :relationships, only: [:update, :destroy]
  post "relationships/:id", to: "relationships#create", as: "create_relationship"
  delete "relationship/:id", to: "relationships#destroy", as: "delete_relationship"

  # Contact
  resources :contacts, only: [:create]

  # API
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :sources, only: [:create, :update]
      resources :quotes, only: [:create, :destroy]
      resources :comments, only: [:create]
      resources :tags, only: [:index, :create]

    end
  end

  get '/user' => "sources#feed", :as => :user_root
  resources :newsletters
end

app/views/shared/left-column/_create-folder.html.erb
<div class="">
  <button type="button" class="new-folder" data-toggle="modal" data-target="#exampleModal">
    <i class="fas fa-plus"></i> New Folder
  </button>
</div>
<!-- Button trigger modal -->

app/views/shared/left-column/_left-column.html.erb
<div class="left-column">
  <%= render('shared/left-column/side-navbar') if user_signed_in? %>
  <%= render 'shared/left-column/create-folder' if user_signed_in? && current_page?(sources_path)%>


</div>

app/views/shared/left-column/_side-navbar.html.erb
<!-- Links -->
<div class="side-navbar">
  <div class="sidebar-links">

    <%= link_to feed_path, class: "" do  %>
      <div class="d-flex sidebar-link ">
        <i class="fab fa-discourse icon"></i>
        <p class="">Start</p>
      </div>
    <% end %>

    <%= link_to discover_feed_path, class: "" do  %>
      <div class="d-flex sidebar-link">
        <i class="fas fa-search icon"></i>
        <p class="">Discover</p>
      </div>
    <% end %>

    <%= link_to notifications_path, class: "" do  %>
      <div class="d-flex sidebar-link">
        <i class="far fa-bell icon"></i>
        <p class="">Notifications</p>

        <% if current_user.notifications.unread.count > 0 %>
          <p class="red-notification-indicator"><%= current_user.notifications.unread.count %></p>
        <% end %>
      </div>
    <% end %>

    <%= link_to coming_soon_path, class: "" do  %>
      <div class="d-flex sidebar-link mb-5">
        <i class="fas fa-chart-line icon"></i>
        <p class="">Charts</p>
      </div>
    <% end %>

    <%= link_to sources_path, class: "" do  %>
      <div class="d-flex sidebar-link">
        <i class="far fa-bookmark icon"></i>
        <p class="">My Captures</p>
      </div>
    <% end %>

    <%= link_to user_profile_overview_path(current_user), class: "" do  %>
      <div class="d-flex sidebar-link mb-0">
        <i class="far fa-user icon"></i>
        <p class="">Profile</p>
      </div>
    <% end %>

  </div>
</div>